language: java
jdk: oraclejdk8
sudo: false
install: true
addons:
  sonarcloud:
    organization: "lastrix-github"
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn cobertura:cobertura && bash <(curl -s https://codecov.io/bash)
